<?
$PERM["bitrix"]["2"]="D";
$PERM["bitrix"]["8"]="D";
$PERM["bitrix"]["3"]="D";
$PERM["bitrix"]["4"]="D";
$PERM["bitrix"]["6"]="D";
$PERM["bitrix"]["7"]="D";
$PERM["bitrix"]["5"]="D";
$PERM["about_servise"]["G8"]="W";
$PERM["ads"]["G8"]="W";
$PERM["index.php"]["G5"]="W";
$PERM["index.php"]["G8"]="W";
$PERM["Merchants_personal_account"]["G7"]="W";
$PERM["Merchants_personal_account"]["*"]="D";
$PERM["Buyers_personal_account"]["G6"]="W";
$PERM["Buyers_personal_account"]["*"]="D";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["/"]["*"]="R";
?>